### ISSUE TITLE
crash: SIGNAL 6 after "bad block" log message

### ISSUE THREAD

**Issue by peertrade** [ElementsProject/lightning#1761]
Running recent github (master) code with spruned.   It seems lightningd believes its a bad block, but that doesn't mean it should crash right after.  Also, when I run

```
time bitcoin-cli getblock 0000000000000000000cb035651dedef4d4d2a38592e88731d59757d0809b23f false
```

It does return data (28 secs), so it's not like spruned isn't running/responding.

```
2018-07-27T01:50:07.919Z lightningd(11240): bitcoin-cli -datadir=/home/lightning/.bitcoin
 getblock 0000000000000000000cb035651dedef4d4d2a38592e88731d59757d0809b23f false: bad block
 'error: {"message":"Server error","code":-32000}?'?
2018-07-27T01:50:08.958Z lightningd(11240): FATAL SIGNAL 6 (version v0.6-127-gf8fa421)
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: common/daemon.c:42 (crashdump) 0x430
ade
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: (null):0 ((null)) 0x7fa3274f4caf
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: (null):0 ((null)) 0x7fa3274f4c37
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: (null):0 ((null)) 0x7fa3274f8027
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: lightningd/log.c:557 (fatal) 0x41619c
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: lightningd/bitcoind.c:413 (process_rawblock) 0x404c46
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: lightningd/bitcoind.c:189 (bcli_finished) 0x404225
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x4696aa
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x4696c9
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x474799
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x474c3f
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: ccan/ccan/tal/tal.c:511 (tal_free) 0x47506a
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: ccan/ccan/io/io.c:443 (io_close) 0x4680a9
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: ccan/ccan/io/poll.c:314 (io_loop) 0x469ab7
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: lightningd/lightningd.c:444 (main) 0x414687
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: (null):0 ((null)) 0x7fa3274dff44
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: (null):0 ((null)) 0x4035ea
2018-07-27T01:50:08.958Z lightningd(11240): backtrace: (null):0 ((null)) 0xffffffffffffffff
```

After restart, all is well until now, 10 minutes later.

**Comment by cdecker** [comment]
We've had some issues with users running `spruned` lately, it appears that some blocks are returned in a format that isn't what `lightningd` expects. I'm wondering if that's because it fetches the block from a non-segwit node and is hence missing witnesses?

Could you compare the output of the `bitcoin-cli` command when running against `spruned` and `bitcoind`?

**Comment by peertrade** [comment]
@cdecker  I don't have an up-to-date full node handy to run getblock against at the moment, but lightningd died again this morning and when I tried the command manually against spruned it took a long time and then gave an error. 

```
$ bitcoin-cli getblock 00000000000000000015d719795ed079d9b544872e84764fc20d8e7dffdb0982 false > /tmp/out
error: {"message":"Server error","code":-32000}
```

 Checking the spruned log, I find:

```
2018-07-27 22:36:19,784 - jsonrpcserver.dispatcher.request - INFO - {'params': ['00000000000000000015d719795ed079d9b544872e84764fc20d8e7dffdb0982', False], 'method': 'getblock', 'id': 1}
2018-07-27 22:38:20,372 - jsonrpcserver.request - ERROR - Traceback (most recent call last):
  File "/home/lightning/spruned/venv/lib/python3.5/site-packages/spruned-0.0.2a3-py3.5.egg/spruned/daemon/bitcoin_p2p/p2p_connection.py", line 262, in get
    response = await future
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 285, in result
    raise CancelledError
concurrent.futures._base.CancelledError
```
which I believe to be a timeout or network error.  A subsequent query succeeded.

So we have a situation where a timeout/network error in spruned is causing lightningd to crash.

I think that lightningd should handle the error gracefully and retry, perhaps backing off after N tries.

**Comment by peertrade** [comment]
From glancing at code in lightningd/bitcoind.c, it appears to me that lightningd is checking the exit code from bitcoin-cli, but is not checking for a json error response when exit code is 0, thus process_rawblock() gets called with following json as input instead of the block hex, and it gives fatal error.

```
{"message":"Server error","code":-32000}
```

I tried to verify that exit code of bitcoin-cli is 0 in this case, but if I simply disconnect network before or during getblock call then bitcoin-cli seems to block forever, so I'm presently unable to reproduce.

**Comment by dan-da** [comment]
ok, I was able to confirm that bitcoin-cli returns exit code 0 when getblock fails with jsonrpc code -32000.

```
$ bitcoin-cli getblock 000000000000000000204c6219796604394a43bb765bdd25a39e9eb7aa7d2cbb
error code: -32000
error message:
Server error
$ echo $?
0
```

**Comment by peertrade** [comment]
Ok, I confirmed that bitcoin-cli returns exit code 0 when getblock fails with json code -32000.

```
$ bitcoin-cli getblock 000000000000000000204c6219796604394a43bb765bdd25a39e9eb7aa7d2cbb
error code: -32000
error message:
Server error
$ echo $?
0
```

**Comment by gdassori** [comment]
Thanks to @cdecker for the contribution, the latest spruned version (0.0.2a5) should fix this. Also available on pypi.
And thanks everyone to use it! :-) :+1:

**Comment by cdecker** [comment]
Might still happen if the bitcoin node (`bitcoind` or `spruned`) is down for more than 1 minute.
