### ISSUE TITLE
getroute is selecting bad route which doesnt have enough capacity over a route which has 

### ISSUE THREAD

**Issue by Sgt-Miller** [ElementsProject/lightning#611]
I have 4 nodes named 0,1,2,3. There are channels from 0 to 1, 1 to 2, 2 to 3, 3 to 0. All channel balance are with the one who started the channel. 
Now, I tried 
`[cli of 1] getroute <id of 0> 100000 1 `
I expected a route 1 -> 2 -> 3 -> 0. But it just gave me a direct route to 0? Does getroute not check channel balances?
Trying to `pay` says capacity exceeded, even though there exists another longer route with enough capacity

**Comment by cdecker** [comment]
This should now be fixed by having `pay` attempt multiple times until either all acceptable options are exhausted or the payment succeeds. @Sgt-Miller can you confirm that this indeed is fixed?

**Comment by ZmnSCPxj** [comment]
Not quite fixed --- I want to modify gossipd, to be given transient information about how many `msatoshi_to_us` each channel has.  And gossipd will completely skip over (not give back in `getroute`) channels with insufficient `msatoshi_to_us`.

Not high priority (maybe 0.6.1 or 0.7) but I want to keep this issue for that.

**Comment by ZmnSCPxj** [comment]
Well, under the scenario given in the original issue, if we let our nodes idle for >20 seconds, our code would return a route 1->0 from a direct `getroute` command on node 1.  The expectation is that the returned route will be 1->2->3->0, since 1 "knows", in principle, that the 1->0 route is unusable.  Our current code will only learn of this if we actually make a payment attempt, so there are still situations where our `getroute` currently written now will return 1->0 instead of the 1->2->3->0 expected by the original issue.

In practice for probably 99.99% of use cases our code works well enough, admittedly, so one can argue the reported issue is moot as it is "no longer a problem in practice".

Still worth keeping around to keep track of this planned optimization.  Or if @Sgt-Miller is fine with it (or times out...), open a new issue to keep track of the planned optimization and close this, I suppose.

**Comment by Sgt-Miller** [comment]
Wow, a lot of progress
