### ISSUE TITLE
Lightning-cli does not return available commands?

### ISSUE THREAD

**Issue by ckcollab** [ElementsProject/lightning#650]
I have a suggestion, I think `lightning-cli` or `lightning-cli --help` should list all available commands.

It would be very helpful for people playing with the new system. For example, `lncli` lists all available commands and that makes it much easier to quickly start playing with. I hope this doesn't come off as ungrateful :( really liking `lightning-charge` right now and I'm trying to figure everything out.

**Comment by jb55** [comment]
You can use `lightning-cli help` for this. This shouldn't be too surprising for people coming from bitcoin-cli ...

**Comment by cdecker** [comment]
Similar to `bitcoin-cli`, `lightning-cli` is a very simple tool that has no a priori knowledge of the available commands, so the `help` command goes out and queries the running daemon about what commands are available. That removes a whole heap of issues with incompatibilities between the daemon and the cli tool :wink: 

Did `lightning-cli help` work for you @ckcollab? If yes I'll close the issue ^^

**Comment by ckcollab** [comment]
Awesome! For anyone interested:

```bash
$ lightning-cli help
[ 
	{ "command" : "dev-blockheight", "description" : "Find out what block height we have" }, 
	{ "command" : "dev-setfees", "description" : "Set feerate in satoshi-per-kw for {immediate}, {normal} and {slow} (each optional).  Returns the value of those three feerates." }, 
	{ "command" : "getnodes", "description" : "Retrieve all nodes in our local network view" }, 
	{ "command" : "getroute", "description" : "Return route to {id} for {msatoshi}, using {riskfactor} and optional {cltv} (default 9)" }, 
	{ "command" : "getchannels", "description" : "List all known channels." }, 
	{ "command" : "invoice", "description" : "Create invoice for {msatoshi} with {label} and {description} with optional {expiry} seconds (default 1 hour)" }, 
	{ "command" : "listinvoice", "description" : "Show invoice {label} (or all, if no {label}))" }, 
	{ "command" : "delinvoice", "description" : "Delete unpaid invoice {label}))" }, 
	{ "command" : "waitanyinvoice", "description" : "Wait for the next invoice to be paid, after {lastpay_index} (if supplied)))" }, 
	{ "command" : "waitinvoice", "description" : "Wait for an incoming payment matching the invoice with {label}" }, 
	{ "command" : "decodepay", "description" : "Parse and decode {bolt11} if possible, using {description} if necessary" }, 
	{ "command" : "help", "description" : "List available commands" }, 
	{ "command" : "stop", "description" : "Shutdown the lightningd process" }, 
	{ "command" : "getlog", "description" : "Get logs, with optional level: [io|debug|info|unusual]" }, 
	{ "command" : "dev-rhash", "description" : "SHA256 of {secret}" }, 
	{ "command" : "dev-crash", "description" : "Call fatal()" }, 
	{ "command" : "getinfo", "description" : "Get general information about this node" }, 
	{ "command" : "sendpay", "description" : "Send along {route} in return for preimage of {rhash}" }, 
	{ "command" : "pay", "description" : "Send payment specified by {bolt11} with optional {msatoshi} (iff {bolt11} does not have amount), {description} (required if {bolt11} uses description hash) and {riskfactor} (default 1.0)" }, 
	{ "command" : "listpayments", "description" : "Get a list of incoming and outgoing payments" }, 
	{ "command" : "connect", "description" : "Connect to {id} at {host} (which can end in ':port' if not default)" }, 
	{ "command" : "getpeers", "description" : "List the current peers, if {level} is set, include {log}s" }, 
	{ "command" : "fundchannel", "description" : "Fund channel with {id} using {satoshi} satoshis" }, 
	{ "command" : "close", "description" : "Close the channel with peer {id}" }, 
	{ "command" : "dev-sign-last-tx", "description" : "Sign and return the last commitment transaction" }, 
	{ "command" : "dev-fail", "description" : "Fail with peer {id}" }, 
	{ "command" : "dev-reenable-commit", "description" : "Reenable the commit timer on peer {id}" }, 
	{ "command" : "dev-ping", "description" : "Offer {peerid} a ping of length {len} asking for {pongbytes}" }, 
	{ "command" : "dev-memdump", "description" : "Dump the memory objects currently used" }, 
	{ "command" : "dev-memleak", "description" : "Dump the memory objects unreferenced" }, 
	{ "command" : "withdraw", "description" : "Send to {destination} address {satoshi} (or 'all') amount via Bitcoin transaction" }, 
	{ "command" : "newaddr", "description" : "Get a new address to fund a channel" }, 
	{ "command" : "addfunds", "description" : "Add funds for lightningd to spend to create channels, using {tx}" }, 
	{ "command" : "listfunds", "description" : "List funds available to the daemon to open channels" } ]
```

It would be awesome to do this automatically for stupid people like myself or show this command when you run `lightning-cli`, currently you only see:

```bash
$ lightning-cli     
lightning-cli: Need at least one argument
Usage: lightning-cli <command> [<params>...]
--lightning-dir   working directory: all other files are relative to this (default: "/root/.lightning")
--rpc-file <arg>  Set JSON-RPC socket (or /dev/tty) (default: "lightning-rpc")
--help|-h         Show this message
--version|-V      print version to standard output and exit

```

For me, it wasn't intuitive (although now it's obvious) to try `help` as a main command. The way `lncli` does it was a bit easier to follow for a beginner.

**Comment by ckcollab** [comment]
For example, `lightning-cli: Need at least one argument` could be replaced with:

```
lightning-cli: Need at least one argument, here are the available options:
    * dev-blockheight    Find out what block height ...
    ...
```

**Comment by cdecker** [comment]
We could do that, but it'd only work if `lightningd` is running already and we can communicate with it. What do you think @rustyrussell, it'd be just setting the `command` to help instead of exiting directly.

**Comment by ckcollab** [comment]
Yeah, I figured there was a good reason it wasn't already there :)

If it's easy to do: awesome, I definitely don't want to get in the way though!

**Comment by artkrasil** [comment]
I have a silly question. How can I start lightning-cli after shutdown?
And also how can i configure public IP?

**Comment by cdecker** [comment]
> I have a silly question. How can I start lightning-cli after shutdown?

You need to start `lightningd`. `lightning-cli` is just the client that talks to your daemon.

> And also how can i configure public IP?

Take a look at the `--addr`, `--bind-addr`, and `--announce-addr`.

**Comment by artkrasil** [comment]
Thanx Christian
1 question is solved
2 - will try to config

**Comment by charltonh** [comment]
I think this is still an issue.  I had no idea about `lightning-cli help` nor is it listed in the `lightning-cli --help`, which in my opinion should be the same thing.  Confusing.

**Comment by jb55** [comment]
> I think this is still an issue. I had no idea about `lightning-cli
> help` nor is it listed in the `lightning-cli --help`, which in my
> opinion should be the same thing. Confusing.

This is the same way `bitcoin-cli` operates, reserving all `bitcoin-cli`
related options to `--help`, and rpc commands to `bitcoin-cli help`

`lightning-cli --help` also mentiones this:

    --help|-h                Show this message. Use the command help (without hyphens -- "lightning-cli help") to get a list of all RPC commands

We were trying to remain consistent with `bitcoin-cli`, I don't have any
strong feelings about listing the cli options after the rpc command
listings, other than the --help output being somewhat verbose.
