### ISSUE TITLE
Python path dependency crashing on NixOS

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/lightning#6637]
I compile, build, and deploy CLN from NixOS. Updating to the latest version crashes, as there's no `python3` system runtime available on NixOS.

Kinda assuming this is related to us now packaging a python plugin with the project? `/usr/bin/env` doesn't work for NixOS systems (i'm using `fetchFromGithub` to compile and build the latest version).

Having a dependency on a system available python path at runtime is really hard to accommodate on NixOS fwiw, we might need to rethink how we're packaging/distributing this plugin to make it compatible (or find a Nix expert).

Fixed by: disabling `clnrest` eg. `disable-plugin=clnrest.py`

```
Aug 29 16:53:40 citrine lightningd[1193376]: /usr/bin/env: 'python3': No such file or directory
Aug 29 16:53:40 citrine lightningd[1193356]: lightningd: lightningd/plugin.c:1912: plugins_init: Assertion `ret == plugins' failed.
Aug 29 16:53:40 citrine lightningd[1193356]: lightningd: FATAL SIGNAL 6 (version v23.08)
Aug 29 16:53:40 citrine lightningd[1193356]: 0x47e3f9 send_backtrace
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x47e493 crashdump
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a3dbef ???
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a8abc7 __pthread_kill_implementation
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a3db45 gsignal
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a284b4 abort
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a283d8 __assert_fail_base.cold.0
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a367b5 __assert_fail
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x450cec plugins_init
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x406182 main
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a2924d __libc_start_call_main
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x7f88c7a29308 __libc_start_main_impl
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0x408cb4 _start
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
Aug 29 16:53:40 citrine lightningd[1193356]: 0xffffffffffffffff ???
Aug 29 16:53:40 citrine lightningd[1193356]:         ???:0
```

**Comment by vincenzopalazzo** [comment]
OK I reproduced also on the fedimint CI, we should fix this

**Comment by vincenzopalazzo** [comment]
OK this should be the one that will go to fix it https://github.com/NixOS/nixpkgs/pull/253310

**Comment by chrisguida** [comment]
Made a patch here that fixes https://github.com/NixOS/nixpkgs/pull/253539

clnrest still doesn't start, but at least it doesn't take down your whole node.

we need to convert clnrest to poetry so we can use https://github.com/nix-community/poetry2nix

otherwise the dependencies are very difficult to install, especially pyln-client and its dependencies which aren't packaged for nix

**Comment by vincenzopalazzo** [comment]
We should avoid to install poetry inside the nix, because poetry is for developers do cln

**Comment by vincenzopalazzo** [comment]
>the alternatives are all much worse AFAICT

Why you can't just install the pip dependencies for cln-rest? or disable cln-rest and give the freedom to the user to install them if they want

>And now that there's a required plugin using python

other plugins have their requirements file, we can not install all the pip packages just because maybe a plugin can use it in the future

**Comment by chrisguida** [comment]
>Why you can't just install the pip dependencies for cln-rest?

I've tried this for hours. I'm open to the possibility that this works, but it's not at all as easy as you're making it sound.

> or disable cln-rest and give the freedom to the user to install them if they want

Yes, this is what my current PR does. Actually you don't need to disable clnrest, it disables itself if it doesn't have the correct dependencies.

>other plugins have their requirements file, we can not install all the pip packages just because maybe a plugin can use it in the future

Clnrest is different from all other plugins. The difference is that clnrest is *required*. We absolutely should make it as easy as possible to install, or else it should not be required.

**Comment by rustyrussell** [comment]
OK, as of 23.08.1 we have a PYTHON ./configure var.  We *could* rewrite the plugin on installation to use this?

Does NixOS have `python` as Python 3?

**Comment by chrisguida** [comment]
@rustyrussell the issue was fixed upstream in [this nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/253539).

The problem is that, because Nix allows running arbitrarily many different versions of things, each package specifies the exact version it needs which is then built and stored at a unique path in the Nix store. There aren't global installs of anything, including `/usr/bin/env`, so the hashbang at the top of `clnrest.py` was failing. There's a utility in nixpkgs to patch hashbangs with the unique version of python that was specifically built to be used as a dependency for the `clightning` package, which wasn't being used, but now is.

The long-term solution is probably for CLN to have a nix flake and explicitly specify its python dependencies (which poetry mostly already takes care of), and have the whole build chain in CI so that stuff like this gets caught automatically. This is something I have [on the back burner](https://github.com/ElementsProject/lightning/pull/6650). Adding Nix will be awesome for wrangling all the different build dependencies IMO, and will benefit everyone, not just NixOS users :)

**Comment by sangbida** [comment]
This issue is being closed as part of issue cleanup.

**Reason**: No recent activity (last updated 800 day

If you believe this issue should remain open, please comment and we can reopen it.
