### ISSUE TITLE
"Failed connected..." message will not stop

### ISSUE THREAD

**Issue by molxyz** [ElementsProject/lightning#836]
I tried to connect to a node (on Testnet) but it hung probably due to node was offline, so I terminated the hanging with Ctrl+C. It stopped the hanging but the log shows it still keeps trying to connect to this node and printing this endless message on the screen: 

`lightning_gossipd(7211): TRACE: Failed connected out for 02c8ebb98a0f133b19fb7bc982ec233d2db32b59d1f1ec178c9bb091a4e2c8d72c, will try again`

https://i.imgur.com/e01D5lR.png

**Comment by ZmnSCPxj** [comment]
Fixed by #813 

Duplicates #681

**Comment by ZmnSCPxj** [comment]
#813 has been merged. If you can stop your node and upgrade, can you confirm this problem is gone and we can close this issue?

**Comment by AndiMacTen** [comment]
The same on my node. I run the latest master and still have the issue. Can show up with some logs later today. 
See my yesterdays comment here https://github.com/ElementsProject/lightning/issues/229

**Comment by ZmnSCPxj** [comment]
@AndiMacTen , #813 was merged about an hour ago (at commit 932dbd8), you are running a master after that commit?   This message should only appear at most 10 times for each peer that cannot be connected to, then say "Failed after %d attempts, giving up after %d seconds".

**Comment by cdecker** [comment]
@ZmnSCPxj #813 likely addresses only attempts initiated by the JSON-RPC `connect` command, not sure if it also affects automated reconnects after a restart or a lost connection.

**Comment by AndiMacTen** [comment]
@ZmnSCPxj my bad, sorry. I'm not able to update as quick as you guys write code. The message doesn't appear anymore with the latest master.

**Comment by molxyz** [comment]
@ZmnSCPxj  Hi, my lightningd is at "commit d03ca59f80368ab9cf197cc5ae4af98753d2d8cf".  Since this report I have opened a channel on Testnet, the transaction has over 100 confirmations  but the channel is stuck at 
`"state" : "CHANNELD_AWAITING_LOCKIN",`
Restarting the node did not solve this.  I guess I can just shut it down and update to the latest master?
