### ISSUE TITLE
Build error v25.09

### ISSUE THREAD

**Issue by Spixmaster** [ElementsProject/lightning#8532]
Trying to build https://aur.archlinux.org/packages/core-lightning fails. The build script with all dependencies is the exact same as for all recent previous versions.

```sh
~
❯ paru -S core-lightning
:: Löse Abhängigkeiten auf…
:: Konflikte berechnen…
:: Interne Konflikte berechnen…

Repo (24) miniupnpc-2.3.3-1  bitcoin-daemon-28.1-2  gunicorn-23.0.0-2  python-aniso8601-9.0.1-8  python-greenlet-3.2.4-1  python-eventlet-0.40.2-1  python-h11-0.16.0-1  python-wsproto-1.2.0-6  python-simple-websocket-1.1.0-1
        python-bidict-0.23.1-4  python-websocket-client-1.8.0-2  python-engineio-4.12.2-1  python-socketio-5.13.0-1  python-flask-socketio-5.5.1-1  python-zope-event-5.1.1-1  python-zope-interface-7.2-1  python-gevent-25.8.2-1
        python-ujson-5.10.0-2  python-gevent-websocket-0.10.1-11  python-grpcio-tools-1.74.1-2  python-grpcio-1.74.1-2  python-json5-0.12.1-1  python-bitarray-3.6.1-1  python-bitstring-4.3.1-1
Repo Make (6) lowdown-1.4.0-1  python-mako-1.3.10-1  rust-1:1.89.0-1  python-editables-0.5-5  python-hatchling-1.27.0-1  python-scikit-build-core-0.11.6-1
Aur (7) python-flask-restx-1.3.0-1  python-base58-2.1.1-1  python-coincurve-21.0.0-2  python-pyln-proto-25.05-1  python-pyln-bolt7-25.05-1  python-pyln-client-25.05-1  core-lightning-25.09-1

:: Mit Überprüfung fortfahren? [J/n]: j

:: Lade PKGBUILDs herunter…
 (7/7) core-lightning-25.09-1                        [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]
:: Änderungen akzeptieren? [J/n]: j
[sudo] Passwort für matheus:
Abhängigkeiten werden aufgelöst …
Nach in Konflikt stehenden Paketen wird gesucht …

Pakete (30) bitcoin-daemon-28.1-2  gunicorn-23.0.0-2  lowdown-1.4.0-1  miniupnpc-2.3.3-1  python-aniso8601-9.0.1-8
            python-bidict-0.23.1-4  python-bitarray-3.6.1-1  python-bitstring-4.3.1-1  python-editables-0.5-5
            python-engineio-4.12.2-1  python-eventlet-0.40.2-1  python-flask-socketio-5.5.1-1  python-gevent-25.8.2-1
            python-gevent-websocket-0.10.1-11  python-greenlet-3.2.4-1  python-grpcio-1.74.1-2
            python-grpcio-tools-1.74.1-2  python-h11-0.16.0-1  python-hatchling-1.27.0-1  python-json5-0.12.1-1
            python-mako-1.3.10-1  python-scikit-build-core-0.11.6-1  python-simple-websocket-1.1.0-1
            python-socketio-5.13.0-1  python-ujson-5.10.0-2  python-websocket-client-1.8.0-2  python-wsproto-1.2.0-6
            python-zope-event-5.1.1-1  python-zope-interface-7.2-1  rust-1:1.89.0-1

Gesamtgröße des Downloads:              80,62 MiB
Gesamtgröße der installierten Pakete:  325,03 MiB

:: Installation fortsetzen? [J/n]
:: Pakete werden empfangen …
 python-eventlet-0.40.2-1-any             1382,4 KiB   597 KiB/s 00:02 [########################################] 100%
 python-grpcio-1.74.1-2-x86_64               3,1 MiB  1203 KiB/s 00:03 [########################################] 100%
 lowdown-1.4.0-1-x86_64                    669,9 KiB   870 KiB/s 00:01 [########################################] 100%
 python-gevent-25.8.2-1-x86_64            1818,7 KiB   556 KiB/s 00:03 [########################################] 100%
 python-zope-interface-7.2-1-x86_64        382,7 KiB   792 KiB/s 00:00 [########################################] 100%
 python-scikit-build-core-0.11.6-1-any     292,3 KiB   642 KiB/s 00:00 [########################################] 100%
 gunicorn-23.0.0-2-any                     176,7 KiB   380 KiB/s 00:00 [########################################] 100%
 python-bitarray-3.6.1-1-x86_64            251,7 KiB   435 KiB/s 00:01 [########################################] 100%
 python-mako-1.3.10-1-any                  171,4 KiB   531 KiB/s 00:00 [########################################] 100%
 python-hatchling-1.27.0-1-any             155,4 KiB   544 KiB/s 00:00 [########################################] 100%
 python-bitstring-4.3.1-1-any              150,9 KiB   383 KiB/s 00:00 [########################################] 100%
 python-grpcio-tools-1.74.1-2-x86_64       148,3 KiB   656 KiB/s 00:00 [########################################] 100%
 python-socketio-5.13.0-1-any              148,6 KiB   622 KiB/s 00:00 [########################################] 100%
 python-engineio-4.12.2-1-any              132,5 KiB   394 KiB/s 00:00 [########################################] 100%
 python-greenlet-3.2.4-1-x86_64            126,3 KiB   616 KiB/s 00:00 [########################################] 100%
 python-websocket-client-1.8.0-2-any       108,2 KiB   410 KiB/s 00:00 [########################################] 100%
 python-h11-0.16.0-1-any                    61,2 KiB   235 KiB/s 00:00 [########################################] 100%
 python-json5-0.12.1-1-any                  57,3 KiB   198 KiB/s 00:00 [########################################] 100%
 python-aniso8601-9.0.1-8-any               97,7 KiB   214 KiB/s 00:00 [########################################] 100%
 python-flask-socketio-5.5.1-1-any          54,5 KiB   328 KiB/s 00:00 [########################################] 100%
 python-ujson-5.10.0-2-x86_64               55,9 KiB   300 KiB/s 00:00 [########################################] 100%
 python-wsproto-1.2.0-6-any                 53,5 KiB   281 KiB/s 00:00 [########################################] 100%
 bitcoin-daemon-28.1-2-x86_64                4,4 MiB   733 KiB/s 00:06 [########################################] 100%
 python-bidict-0.23.1-4-any                 47,7 KiB   348 KiB/s 00:00 [########################################] 100%
 miniupnpc-2.3.3-1-x86_64                   47,7 KiB   353 KiB/s 00:00 [########################################] 100%
 python-gevent-websocket-0.10.1-11-any      45,7 KiB   286 KiB/s 00:00 [########################################] 100%
 python-simple-websocket-1.1.0-1-any        26,2 KiB   146 KiB/s 00:00 [########################################] 100%
 python-editables-0.5-5-any                 10,9 KiB  66,4 KiB/s 00:00 [########################################] 100%
 python-zope-event-5.1.1-1-any              10,3 KiB  40,5 KiB/s 00:00 [########################################] 100%
 rust-1:1.89.0-1-x86_64                     66,7 MiB  2,21 MiB/s 00:30 [########################################] 100%
 Gesamt (30/30)                             80,6 MiB  2,67 MiB/s 00:30 [########################################] 100%
(30/30) Schlüssel im Schlüsselbund werden geprüft                      [########################################] 100%
(30/30) Paket-Integrität wird überprüft                                [########################################] 100%
(30/30) Paket-Dateien werden geladen                                   [########################################] 100%
(30/30) Auf Dateikonflikte wird geprüft                                [########################################] 100%
(30/30) Verfügbarer Festplattenspeicher wird ermittelt                 [########################################] 100%
:: Paketänderungen werden verarbeitet …
( 1/30) Installiert wird lowdown                                       [########################################] 100%
( 2/30) Installiert wird python-mako                                   [########################################] 100%
Optionale Abhängigkeiten für python-mako
    python-babel: for i18n features
    python-beaker: for caching support
    python-dogpile.cache: for caching support
    python-pygments: for syntax highlighting [Installiert]
    python-pytest: for testing utilities [Installiert]
( 3/30) Installiert wird rust                                          [########################################] 100%
Optionale Abhängigkeiten für rust
    gdb: rust-gdb script [Installiert]
    lldb: rust-lldb script
( 4/30) Installiert wird miniupnpc                                     [########################################] 100%
( 5/30) Installiert wird bitcoin-daemon                                [########################################] 100%
( 6/30) Installiert wird gunicorn                                      [########################################] 100%
Optionale Abhängigkeiten für gunicorn
    python-eventlet: for asynchronous request handling with eventlet [ausstehend]
    python-gevent: for asynchronous request handling with gevent [ausstehend]
    python-setproctitle: for process renaming [Installiert]
    python-tornado: for asynchronous request handling with tornado
( 7/30) Installiert wird python-aniso8601                              [########################################] 100%
( 8/30) Installiert wird python-greenlet                               [########################################] 100%
( 9/30) Installiert wird python-eventlet                               [########################################] 100%
Optionale Abhängigkeiten für python-eventlet
    python-httplib2: non-blocking HTTP support
    python-psycopg2: non-blocking PostgreSQL support
    python-pyopenssl: non-blocking SSL support [Installiert]
    python-pyzmq: non-blocking ZeroMQ support
(10/30) Installiert wird python-h11                                    [########################################] 100%
(11/30) Installiert wird python-wsproto                                [########################################] 100%
(12/30) Installiert wird python-simple-websocket                       [########################################] 100%
(13/30) Installiert wird python-bidict                                 [########################################] 100%
(14/30) Installiert wird python-websocket-client                       [########################################] 100%
(15/30) Installiert wird python-engineio                               [########################################] 100%
Optionale Abhängigkeiten für python-engineio
    python-aiohttp: aiohttp driver [Installiert]
    python-eventlet: eventlet driver [Installiert]
    python-gevent-websocket: gevent driver [ausstehend]
    python-gevent: gevent driver [ausstehend]
    python-tornado: tornado driver
(16/30) Installiert wird python-socketio                               [########################################] 100%
Optionale Abhängigkeiten für python-socketio
    python-tornado: tornado asyncio webserver
(17/30) Installiert wird python-flask-socketio                         [########################################] 100%
(18/30) Installiert wird python-zope-event                             [########################################] 100%
(19/30) Installiert wird python-zope-interface                         [########################################] 100%
(20/30) Installiert wird python-gevent                                 [########################################] 100%
(21/30) Installiert wird python-ujson                                  [########################################] 100%
(22/30) Installiert wird python-gevent-websocket                       [########################################] 100%
(23/30) Installiert wird python-grpcio-tools                           [########################################] 100%
(24/30) Installiert wird python-grpcio                                 [########################################] 100%
(25/30) Installiert wird python-json5                                  [########################################] 100%
(26/30) Installiert wird python-bitarray                               [########################################] 100%
(27/30) Installiert wird python-bitstring                              [########################################] 100%
(28/30) Installiert wird python-editables                              [########################################] 100%
(29/30) Installiert wird python-hatchling                              [########################################] 100%
(30/30) Installiert wird python-scikit-build-core                      [########################################] 100%
:: Post-transaction-Hooks werden gestartet …
(1/4) Creating system user accounts...
(2/4) Reloading system manager configuration...
(3/4) Creating temporary files...
(4/4) Arming ConditionNeedsUpdate...
devel Informationen werden empfangen...
==> Erstelle Paket: python-flask-restx 1.3.0-1 (Mi 03 Sep 2025 09:03:42 CEST)
==> Empfange Quellen...
  -> Lade flask-restx-1.3.0.tar.gz herunter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2748k  100 2748k    0     0  2385k      0  0:00:01  0:00:01 --:--:-- 3098k
==> Überprüfe source Dateien mit sha256sums...
    flask-restx-1.3.0.tar.gz ... Erfolg
==> Erstelle Paket: python-flask-restx 1.3.0-1 (Mi 03 Sep 2025 09:03:44 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> flask-restx-1.3.0.tar.gz gefunden
==> Überprüfe source Dateien mit sha256sums...
    flask-restx-1.3.0.tar.gz ... Erfolg
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Entpacke flask-restx-1.3.0.tar.gz mit bsdtar
==> Quellen sind fertig.
python-flask-restx-1.3.0-1: Lese pkg Liste…
==> Erstelle Paket: python-flask-restx 1.3.0-1 (Mi 03 Sep 2025 09:03:45 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> WARNUNG: Verwende bestehenden $srcdir/ Baum
==> Beginne build()...
* Getting build dependencies for wheel...
/usr/lib/python3.13/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/usr/lib/python3.13/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'dev_require'
  warnings.warn(msg)
/usr/lib/python3.13/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
!!

        ********************************************************************************
        Please consider removing the following classifiers in favor of a SPDX license expression:

        License :: OSI Approved :: BSD License

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************

!!
  self._finalize_license_expression()
running egg_info
writing flask_restx.egg-info/PKG-INFO
writing dependency_links to flask_restx.egg-info/dependency_links.txt
writing requirements to flask_restx.egg-info/requires.txt
writing top-level names to flask_restx.egg-info/top_level.txt
reading manifest file 'flask_restx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'flask_restx.egg-info/SOURCES.txt'
* Building wheel...
/usr/lib/python3.13/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/usr/lib/python3.13/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'dev_require'
  warnings.warn(msg)
/usr/lib/python3.13/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
!!

        ********************************************************************************
        Please consider removing the following classifiers in favor of a SPDX license expression:

        License :: OSI Approved :: BSD License

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************

!!
  self._finalize_license_expression()
running bdist_wheel
/usr/lib/python3.13/site-packages/setuptools/_distutils/cmd.py:135: SetuptoolsDeprecationWarning: bdist_wheel.universal is deprecated
!!

        ********************************************************************************
        With Python 2.7 end-of-life, support for building universal wheels
        (i.e., wheels that support both Python 2 and Python 3)
        is being obviated.
        Please discontinue using this option, or if you still need it,
        file an issue with pypa/setuptools describing your use case.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.
        ********************************************************************************

!!
  self.finalize_options()
running build
running build_py
creating build/lib/flask_restx
copying flask_restx/fields.py -> build/lib/flask_restx
copying flask_restx/resource.py -> build/lib/flask_restx
copying flask_restx/marshalling.py -> build/lib/flask_restx
copying flask_restx/_http.py -> build/lib/flask_restx
copying flask_restx/utils.py -> build/lib/flask_restx
copying flask_restx/swagger.py -> build/lib/flask_restx
copying flask_restx/model.py -> build/lib/flask_restx
copying flask_restx/cors.py -> build/lib/flask_restx
copying flask_restx/errors.py -> build/lib/flask_restx
copying flask_restx/apidoc.py -> build/lib/flask_restx
copying flask_restx/postman.py -> build/lib/flask_restx
copying flask_restx/mask.py -> build/lib/flask_restx
copying flask_restx/reqparse.py -> build/lib/flask_restx
copying flask_restx/api.py -> build/lib/flask_restx
copying flask_restx/namespace.py -> build/lib/flask_restx
copying flask_restx/inputs.py -> build/lib/flask_restx
copying flask_restx/representations.py -> build/lib/flask_restx
copying flask_restx/__init__.py -> build/lib/flask_restx
copying flask_restx/__about__.py -> build/lib/flask_restx
creating build/lib/flask_restx/schemas
copying flask_restx/schemas/__init__.py -> build/lib/flask_restx/schemas
running egg_info
writing flask_restx.egg-info/PKG-INFO
writing dependency_links to flask_restx.egg-info/dependency_links.txt
writing requirements to flask_restx.egg-info/requires.txt
writing top-level names to flask_restx.egg-info/top_level.txt
reading manifest file 'flask_restx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'flask_restx.egg-info/SOURCES.txt'
/usr/lib/python3.13/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'flask_restx.static' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'flask_restx.static' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'flask_restx.static' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'flask_restx.static' to be distributed and are
        already explicitly excluding 'flask_restx.static' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/usr/lib/python3.13/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'flask_restx.static.files' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'flask_restx.static.files' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'flask_restx.static.files' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'flask_restx.static.files' to be distributed and are
        already explicitly excluding 'flask_restx.static.files' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
/usr/lib/python3.13/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'flask_restx.templates' is absent from the `packages` configuration.
!!

        ********************************************************************************
        ############################
        # Package would be ignored #
        ############################
        Python recognizes 'flask_restx.templates' as an importable package[^1],
        but it is absent from setuptools' `packages` configuration.

        This leads to an ambiguous overall configuration. If you want to distribute this
        package, please make sure that 'flask_restx.templates' is explicitly added
        to the `packages` configuration field.

        Alternatively, you can also rely on setuptools' discovery methods
        (for example by using `find_namespace_packages(...)`/`find_namespace:`
        instead of `find_packages(...)`/`find:`).

        You can read more about "package discovery" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

        If you don't want 'flask_restx.templates' to be distributed and are
        already explicitly excluding 'flask_restx.templates' via
        `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
        you can try to use `exclude_package_data`, or `include-package-data=False` in
        combination with a more fine grained `package-data` configuration.

        You can read more about "package data files" on setuptools documentation page:

        - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


        [^1]: For Python, any directory (with suitable naming) can be imported,
              even if it does not contain any `.py` files.
              On the other hand, currently there is no concept of package data
              directory, all directories are treated like packages.
        ********************************************************************************

!!
  check.warn(importable)
creating build/lib/flask_restx/static
copying flask_restx/static/droid-sans.css -> build/lib/flask_restx/static
copying flask_restx/static/favicon-16x16.png -> build/lib/flask_restx/static
copying flask_restx/static/favicon-32x32.png -> build/lib/flask_restx/static
copying flask_restx/static/oauth2-redirect.html -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-bundle.js -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-bundle.js.map -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-es-bundle-core.js -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-es-bundle-core.js.map -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-es-bundle.js -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-es-bundle.js.map -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-standalone-preset.js -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui-standalone-preset.js.map -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui.css -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui.css.map -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui.js -> build/lib/flask_restx/static
copying flask_restx/static/swagger-ui.js.map -> build/lib/flask_restx/static
creating build/lib/flask_restx/static/files
copying flask_restx/static/files/.npmignore -> build/lib/flask_restx/static/files
copying flask_restx/static/files/droid-sans-latin-400.woff -> build/lib/flask_restx/static/files
copying flask_restx/static/files/droid-sans-latin-400.woff2 -> build/lib/flask_restx/static/files
copying flask_restx/static/files/droid-sans-latin-700.woff -> build/lib/flask_restx/static/files
copying flask_restx/static/files/droid-sans-latin-700.woff2 -> build/lib/flask_restx/static/files
creating build/lib/flask_restx/templates
copying flask_restx/templates/swagger-ui-css.html -> build/lib/flask_restx/templates
copying flask_restx/templates/swagger-ui-libs.html -> build/lib/flask_restx/templates
copying flask_restx/templates/swagger-ui.html -> build/lib/flask_restx/templates
copying flask_restx/schemas/oas-2.0.json -> build/lib/flask_restx/schemas
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/flask_restx
copying build/lib/flask_restx/fields.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/resource.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/marshalling.py -> build/bdist.linux-x86_64/wheel/./flask_restx
creating build/bdist.linux-x86_64/wheel/flask_restx/templates
copying build/lib/flask_restx/templates/swagger-ui-libs.html -> build/bdist.linux-x86_64/wheel/./flask_restx/templates
copying build/lib/flask_restx/templates/swagger-ui-css.html -> build/bdist.linux-x86_64/wheel/./flask_restx/templates
copying build/lib/flask_restx/templates/swagger-ui.html -> build/bdist.linux-x86_64/wheel/./flask_restx/templates
copying build/lib/flask_restx/_http.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/utils.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/swagger.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/model.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/cors.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/errors.py -> build/bdist.linux-x86_64/wheel/./flask_restx
creating build/bdist.linux-x86_64/wheel/flask_restx/schemas
copying build/lib/flask_restx/schemas/oas-2.0.json -> build/bdist.linux-x86_64/wheel/./flask_restx/schemas
copying build/lib/flask_restx/schemas/__init__.py -> build/bdist.linux-x86_64/wheel/./flask_restx/schemas
copying build/lib/flask_restx/apidoc.py -> build/bdist.linux-x86_64/wheel/./flask_restx
creating build/bdist.linux-x86_64/wheel/flask_restx/static
copying build/lib/flask_restx/static/oauth2-redirect.html -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-es-bundle.js -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/favicon-16x16.png -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-standalone-preset.js -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-bundle.js.map -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/droid-sans.css -> build/bdist.linux-x86_64/wheel/./flask_restx/static
creating build/bdist.linux-x86_64/wheel/flask_restx/static/files
copying build/lib/flask_restx/static/files/droid-sans-latin-400.woff2 -> build/bdist.linux-x86_64/wheel/./flask_restx/static/files
copying build/lib/flask_restx/static/files/.npmignore -> build/bdist.linux-x86_64/wheel/./flask_restx/static/files
copying build/lib/flask_restx/static/files/droid-sans-latin-400.woff -> build/bdist.linux-x86_64/wheel/./flask_restx/static/files
copying build/lib/flask_restx/static/files/droid-sans-latin-700.woff2 -> build/bdist.linux-x86_64/wheel/./flask_restx/static/files
copying build/lib/flask_restx/static/files/droid-sans-latin-700.woff -> build/bdist.linux-x86_64/wheel/./flask_restx/static/files
copying build/lib/flask_restx/static/swagger-ui.js.map -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-bundle.js -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/favicon-32x32.png -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-es-bundle.js.map -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-es-bundle-core.js -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-es-bundle-core.js.map -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui.css -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui.css.map -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui-standalone-preset.js.map -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/static/swagger-ui.js -> build/bdist.linux-x86_64/wheel/./flask_restx/static
copying build/lib/flask_restx/postman.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/mask.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/reqparse.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/api.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/namespace.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/inputs.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/representations.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/__init__.py -> build/bdist.linux-x86_64/wheel/./flask_restx
copying build/lib/flask_restx/__about__.py -> build/bdist.linux-x86_64/wheel/./flask_restx
running install_egg_info
Copying flask_restx.egg-info to build/bdist.linux-x86_64/wheel/./flask_restx-1.3.0-py3.13.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/flask_restx-1.3.0.dist-info/WHEEL
creating '/home/matheus/.cache/paru/clone/python-flask-restx/src/flask-restx-1.3.0/dist/.tmp-61ddy61e/flask_restx-1.3.0-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'flask_restx/__about__.py'
adding 'flask_restx/__init__.py'
adding 'flask_restx/_http.py'
adding 'flask_restx/api.py'
adding 'flask_restx/apidoc.py'
adding 'flask_restx/cors.py'
adding 'flask_restx/errors.py'
adding 'flask_restx/fields.py'
adding 'flask_restx/inputs.py'
adding 'flask_restx/marshalling.py'
adding 'flask_restx/mask.py'
adding 'flask_restx/model.py'
...
checking target system type... x86_64-pc-linux-gnu
checking for gcc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking whether cc understands -c and -o together... yes
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... (cached) cc
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... (cached) none needed
checking whether cc understands -c and -o together... (cached) yes
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking for dwz... no
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... (cached) ranlib
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking unwind.h usability... yes
checking unwind.h presence... yes
checking for unwind.h... yes
checking for _Unwind_Backtrace... yes
checking for -funwind-tables option... yes
checking for -frandom-seed=string option... yes
checking whether cc supports -W... yes
checking whether cc supports -Wall... yes
checking whether cc supports -Wwrite-strings... yes
checking whether cc supports -Wstrict-prototypes... yes
checking whether cc supports -Wmissing-prototypes... yes
checking whether cc supports -Wold-style-definition... yes
checking whether cc supports -Wmissing-format-attribute... yes
checking whether cc supports -Wcast-qual... yes
checking whether cc supports -Wattributes... yes
checking whether cc supports -Wunknown-attributes... no
checking whether cc supports -Wpointer-arith... yes
checking for _Unwind_GetIPInfo... yes
checking __sync extensions... yes
checking __atomic extensions... yes
checking output filetype... elf64
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for mmap... yes
checking link.h usability... yes
checking link.h presence... yes
checking for link.h... yes
checking sys/link.h usability... no
checking sys/link.h presence... no
checking for sys/link.h... no
checking for dl_iterate_phdr... yes
checking mach-o/dyld.h usability... no
checking mach-o/dyld.h presence... no
checking for mach-o/dyld.h... no
checking sys/ldr.h usability... no
checking sys/ldr.h presence... no
checking for sys/ldr.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for tlhelp32.h... no
checking for fcntl... yes
checking whether strnlen is declared... yes
checking whether getpagesize is declared... yes
checking for lstat... yes
checking for readlink... yes
checking for getexecname... no
checking whether _pgmptr is declared... no
checking for KERN_PROC... no
checking for KERN_PROG_ARGS... no
checking for clock_gettime... yes
checking whether -pthread is supported... yes
checking whether -gdwarf-5 is supported... yes
checking for compress in -lz... yes
checking whether --build-id is supported... yes
checking whether --compress-debug-sections=zlib-gnu is supported... yes
checking whether --compress-debug-sections=zlib-gabi is supported... yes
checking for ZSTD_compress in -lzstd... yes
checking whether --compress-debug-sections=zstd is supported... yes
checking for objcopy... objcopy
checking for readelf... readelf
checking whether objcopy supports debuglink... yes
checking for dsymutil... dsymutil
checking for nm... /usr/bin/nm -B
checking for xz... xz
checking for comm... comm
checking for lzma_auto_decoder in -llzma... yes
checking whether tests can run... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating backtrace-supported.h
config.status: creating install-debuginfo-for-buildid.sh
config.status: creating config.h
config.status: executing libtool commands
config.status: executing default commands
make[1]: Verzeichnis „/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace-build“ wird betreten
make  all-am
make[2]: Verzeichnis „/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace-build“ wird betreten
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=atomic.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o atomic.lo ../../libbacktrace/atomic.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=atomic.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/atomic.c -o atomic.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=dwarf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o dwarf.lo ../../libbacktrace/dwarf.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=dwarf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/dwarf.c -o dwarf.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=fileline.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o fileline.lo ../../libbacktrace/fileline.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=fileline.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/fileline.c -o fileline.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=posix.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o posix.lo ../../libbacktrace/posix.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=posix.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/posix.c -o posix.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=print.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o print.lo ../../libbacktrace/print.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=print.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/print.c -o print.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=sort.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o sort.lo ../../libbacktrace/sort.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=sort.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/sort.c -o sort.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o state.lo ../../libbacktrace/state.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/state.c -o state.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=backtrace.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o backtrace.lo ../../libbacktrace/backtrace.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=backtrace.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/backtrace.c -o backtrace.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=simple.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o simple.lo ../../libbacktrace/simple.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=simple.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/simple.c -o simple.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=elf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o elf.lo ../../libbacktrace/elf.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=elf.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/elf.c -o elf.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=mmapio.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o mmapio.lo ../../libbacktrace/mmapio.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=mmapio.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/mmapio.c -o mmapio.o
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I../../libbacktrace    -funwind-tables -frandom-seed=mmap.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2 -c -o mmap.lo ../../libbacktrace/mmap.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../../libbacktrace -funwind-tables -frandom-seed=mmap.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith -g -O2 -c ../../libbacktrace/mmap.c -o mmap.o
/bin/sh ./libtool  --tag=CC   --mode=link cc -funwind-tables -frandom-seed=libbacktrace.la -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -Wno-attributes -Wpointer-arith  -g -O2  -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto   -Og -o libbacktrace.la -rpath / atomic.lo dwarf.lo fileline.lo posix.lo print.lo sort.lo state.lo backtrace.lo simple.lo elf.lo mmapio.lo mmap.lo
libtool: link: ar --plugin /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/liblto_plugin.so cru .libs/libbacktrace.a  atomic.o dwarf.o fileline.o posix.o print.o sort.o state.o backtrace.o simple.o elf.o mmapio.o mmap.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib --plugin /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/liblto_plugin.so .libs/libbacktrace.a
libtool: link: ( cd ".libs" && rm -f "libbacktrace.la" && ln -s "../libbacktrace.la" "libbacktrace.la" )
make[2]: Verzeichnis „/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace-build“ wird verlassen
make[1]: Verzeichnis „/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace-build“ wird verlassen
make -C external/build-x86_64-pc-linux-gnu/libbacktrace-build DESTDIR=$(pwd)/external/build-x86_64-pc-linux-gnu install-exec
make[1]: Verzeichnis „/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace-build“ wird betreten
 /usr/bin/mkdir -p '/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libbacktrace.la '/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/'
libtool: install: /usr/bin/install -c .libs/libbacktrace.lai /home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace.la
libtool: install: /usr/bin/install -c .libs/libbacktrace.a /home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace.a
libtool: install: chmod 644 /home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace.a
libtool: install: ranlib --plugin /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/liblto_plugin.so /home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace.a
libtool: install: warning: remember to run `libtool --finish /'
make[1]: Verzeichnis „/home/matheus/.cache/paru/clone/core-lightning/src/core-lightning/external/build-x86_64-pc-linux-gnu/libbacktrace-build“ wird verlassen
ar libccan.a
ar: creating libccan.a
ld ccan/ccan/cdump/tools/cdump-enumstr
ccan/ccan/cdump/tools/cdump-enumstr common/htlc_state.h > common/htlc_state_names_gen.h
wiregen common/status_wiregen.h
wiregen common/peer_status_wiregen.h
wiregen common/scb_wiregen.h
wiregen wire/peer_wiregen.h
wiregen wire/onion_wiregen.h
wiregen wire/bolt12_wiregen.h
wiregen wire/channel_type_wiregen.h
printgen wire/bolt12_printgen.h
printgen wire/peer_printgen.h
printgen wire/onion_printgen.h
wiregen hsmd/hsmd_wiregen.h
wiregen gossipd/gossipd_wiregen.h
wiregen gossipd/gossip_store_wiregen.h
wiregen openingd/openingd_wiregen.h
wiregen openingd/dualopend_wiregen.h
ccan/ccan/cdump/tools/cdump-enumstr channeld/full_channel_error.h > channeld/full_channel_error_names_gen.h
wiregen channeld/channeld_wiregen.h
wiregen closingd/closingd_wiregen.h
wiregen onchaind/onchaind_wiregen.h
ccan/ccan/cdump/tools/cdump-enumstr onchaind/onchain_types.h > onchaind/onchain_types_names_gen.h
wiregen connectd/connectd_wiregen.h
wiregen connectd/connectd_gossipd_wiregen.h
ccan/ccan/cdump/tools/cdump-enumstr lightningd/channel_state.h > lightningd/channel_state_names_gen.h
tools/generate-wire.py --page header tools/test/test_gen.h test_type < tools/test/test_cases > tools/test/test_gen.h
tools/generate-wire.py -P --page header tools/test/print_gen.h test_type < tools/test/test_cases > tools/test/print_gen.h
GEN plugins/list_of_builtin_plugins_gen.h
cc plugins/sql.c
cc plugins/libplugin.c
cc common/trace.c
cc bitcoin/base58.c
cc bitcoin/block.c
cc bitcoin/chainparams.c
cc bitcoin/feerate.c
cc bitcoin/preimage.c
cc bitcoin/privkey.c
cc bitcoin/psbt.c
cc bitcoin/pubkey.c
cc bitcoin/script.c
cc bitcoin/shadouble.c
cc bitcoin/short_channel_id.c
cc bitcoin/signature.c
cc bitcoin/tx.c
cc bitcoin/varint.c
cc common/addr.c
cc common/amount.c
cc common/autodata.c
cc common/coin_mvt.c
cc common/base32.c
cc common/bech32.c
cc common/bech32_util.c
cc common/bigsize.c
cc common/bolt11.c
cc common/channel_id.c
cc common/daemon.c
cc common/deprecation.c
cc common/features.c
cc common/hash_u5.c
cc common/json_command.c
cc common/json_param.c
cc common/json_parse.c
cc common/json_parse_simple.c
cc common/json_filter.c
cc common/json_stream.c
cc common/lease_rates.c
cc common/memleak.c
cc common/node_id.c
cc common/plugin.c
cc common/psbt_open.c
cc common/pseudorand.c
cc common/random_select.c
cc common/splice_script.c
cc common/setup.c
cc common/status_levels.c
cc common/utils.c
cc common/version.c
cc common/wireaddr.c
printgen wire/channel_type_printgen.h
cc wire/fromwire.c
wiregen wire/peer_wiregen.c
cc wire/peer_wiregen.c
cc wire/tlvstream.c
cc wire/towire.c
cc common/gossip_store.c
wiregen gossipd/gossip_store_wiregen.c
cc gossipd/gossip_store_wiregen.c
ld plugins/sql
xgettext wallet/statements_gettextgen.po
sql-rewrite wallet/db_sqlite3_sqlgen.c
sql-rewrite wallet/db_postgres_sqlgen.c
python3 -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/node.proto --python_out=contrib/pyln-grpc-proto/pyln/grpc/ --grpc_python_out=contrib/pyln-grpc-proto/pyln/grpc/ --experimental_allow_proto3_optional
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756883369.145739   58833 command_line_interface.cc:1557] Built-in generator --grpc_python_out specifies a maximum edition 2023 which is not the protoc maximum 2024.
make: *** [Makefile:404: contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
Fehler: ‚core-lightning-25.09-1‘ konnte nicht erstellt werden:
Fehler: Pakete konnten nicht erstellt werden: core-lightning-25.09-1
```

**Comment by daywalker90** [comment]
I tried to reproduce this on debian with your versions of protoc 32.0 and grpcio 1.74 and grpcio-tools 1.74 but could not hit any error.
I'm not familiar with arch install scripts but i've glanced at it and noticed it's not using uv for python dependency management, this can easily lead to problems and might be the cause of this or it's the newer protoc version from the protobuf package.

But either way the error message "specifies a maximum edition 2023 which is not the protoc maximum 2024" is confusing to me since it should support both afaik.

(Also i don't see you setting RUST_PROFILE=release anywhere)

**Comment by bitcoinlizard** [comment]
I am having the same issue building with Arch Linux.  I found that I was no longer able to build version 25.5 on my up to date Arch system.

I tried older versions of protobuf, python-protobuf, python-grpcio-tools but was unable to get the package to build.  These seemed to be more package compatibility issues vs the above noted build error.

**Comment by bitcoinlizard** [comment]
For what it's worth I was able to get this to build by downgrading these packages to these versions:
protobuf 29.3
python-protobuf 29.3
python-grpcio 1.70.1
python-grpcio-tools 1.70.1
abseil-cpp 20250127.1

These are the current versions in the Arch repository:
protobuf 32.0
python-protobuf 32.0
python-grpcio 1.74.1
python-grpcio-tools 1.74.1
abseil-cpp 20250814.0

I will not try to run it however as this may break other things on the system and I suspect 25.5 to 25.9 will have irreversible DB upgrades.

**Comment by Rav3nPL** [comment]
For me its failing because file 
```
site-packages/pyln/__init__.py
```
is used by python-pyln-bolt7, python-pyln-proto AND python-pyln-client

**Comment by cotsuka** [comment]
@Rav3nPL I maintain those AUR packages and noticed that as well. If I have time over the weekend (or anybody does), I can write some patches to build them into actually separate packages. Probably something we can consider for upstreaming if it makes sense.

**Comment by rustyrussell** [comment]
Is this fixed by https://github.com/ElementsProject/lightning/pull/8517 ?  If so, we should expedite that for the point release...

**Comment by cotsuka** [comment]
@rustyrussell Confirming my AUR packages now seem to install properly. Applied #8517 as a [patch](https://patch-diff.githubusercontent.com/raw/ElementsProject/lightning/pull/8517.patch) and no issues.

**Comment by Spixmaster** [comment]
With version v25.12, the issue is still present.

```sh
python3 -m grpc_tools.protoc -I cln-grpc/proto cln-grpc/proto/node.proto --python_out=contrib/pyln-grpc-proto/pyln/grpc/ --grpc_python_out=contrib/pyln-grpc-proto/pyln/grpc/ --experimental_allow_proto3_optional
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1765454230.395035  728720 command_line_interface.cc:1568] Built-in generator --grpc_python_out specifies a maximum edition 2023 which is not the protoc maximum 2024.
make: *** [Makefile:441: contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py] Fehler 1
```

@bitcoinlizard and @cotsuka , can you confirm this?

**Comment by Spixmaster** [comment]
It seems to be a version mismatch in the Arch Linux repositories, https://aur.archlinux.org/packages/core-lightning#comment-1051265 .
